# Generated by Django 4.2 on 2025-11-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
