# Generated by Django 4.2 on 2025-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
